default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: backend_authentication_development

test:
  <<: *default
  database: backend_authentication_test

production:
  <<: *default
  database: backend_authentication_production
  username: backend_authentication
  password: <%= ENV["BACKEND_AUTHENTICATION_DATABASE_PASSWORD"] %>
